import { EmotionOption } from './types';

export const EMOTION_PRESETS: EmotionOption[] = [
  { id: 'standing', label: 'Standing', tags: 'looking at viewer, arms at sides' },
  { id: 'angry', label: 'Angry', tags: 'looking at viewer, angry, anger vein, wavy mouth, open mouth, hands on own hips, leaning forward' },
  { id: 'annoyed', label: 'Annoyed', tags: 'looking at viewer, half-closed eyes, annoyed, frown, parted lips, v-shaped eyebrows' },
  { id: 'aroused', label: 'Aroused', tags: 'looking at viewer, aroused, heavy breathing, blush, half-closed eyes, parted lips, furrowed brow' },
  { id: 'blushing_shyly', label: 'Blushing Shyly', tags: 'looking at viewer, embarrassed, full-face blush, half-closed eyes, raised eyebrows, covering mouth, hand over own mouth, own hands together, clenched hands' },
  { id: 'coughing', label: 'Coughing', tags: 'closed eyes, frown, coughing, sick, hand to own mouth, open mouth, furrowed brow, raised eyebrows, wavy mouth' },
  { id: 'confused', label: 'Confused', tags: 'looking at viewer, confused, !?, parted lips, :o, furrowed brow, frown, raised eyebrows, hand on own chest, sweat' },
  { id: 'contemptuous', label: 'Contemptuous', tags: 'looking at viewer, disgust, expressionless, frown, shaded face, half-closed eyes, parted lips, arms at sides' },
  { id: 'crying_eyes_closed', label: 'Crying (Closed Eyes)', tags: 'looking down, closed eyes, sad, frown, crying, tears, rubbing eyes, wiping tears, open mouth, wavy mouth, clenched hand' },
  { id: 'crying_eyes_open', label: 'Crying (Open Eyes)', tags: 'looking at viewer, crying, crying with eyes open, tears, wavy mouth, parted lips, hand on own chest, raised eyebrows' },
  { id: 'curious', label: 'Curious', tags: 'looking at viewer, curious, ?, :o, finger to mouth' },
  { id: 'depressed', label: 'Depressed', tags: 'looking down, half-closed eyes, depressed, frown, parted lips, shaded face, triangle mouth, wavy mouth, raised eyebrows, sad, hand to own arm, arm under breasts, arm at side' },
  { id: 'disappointed', label: 'Disappointed', tags: 'looking at viewer, disappointed, raised eyebrows, sigh, half-closed eyes, annoyed, parted lips, wavy mouth, hand on own arm, holding own arm, hand in own hair' },
  { id: 'disgusted', label: 'Disgusted', tags: 'looking at viewer, shaded face, disgust, frown, half-closed eye, uneven eyes, hand over own mouth, covering mouth, furrowed brow, raised eyebrows, sweat' },
  { id: 'embarrassed', label: 'Embarrassed', tags: 'looking at viewer, embarrassed, @_@, raised eyebrows, furrowed brow, blush, half-closed eyes, wavy mouth, open mouth, hand to own mouth' },
  { id: 'flustered', label: 'Flustered', tags: 'looking at viewer, surprised, flustered, embarrassed, shy, blush, raised eyebrows, chestnut mouth, hand in own hair, playing with own hair, twirling hair, sweat' },
  { id: 'fidgeting_shyly', label: 'Fidgeting Shyly', tags: 'looking down, half-closed eyes, blush, embarrassed, closed mouth, index fingers together, fidgeting' },
  { id: 'full_face_blush', label: 'Full-face Blush', tags: 'looking down, full-face blush, parted lips, wavy mouth, embarrassed, sweat, @_@, flying sweatdrops, hands on own face, covering face, head steam, steam' },
  { id: 'giggling', label: 'Giggling', tags: 'happy, smile, closed eyes, ^ ^, hand over own mouth, covering mouth' },
  { id: 'guilty', label: 'Guilty', tags: 'looking down, half-closed eyes, sad, v arms' },
  { id: 'indifferent', label: 'Indifferent', tags: 'looking at viewer, expressionless, :/, jitome, arms at sides' },
  { id: 'joyful', label: 'Joyful', tags: 'happy, closed eyes, smile, open mouth, own hands together, palms together, praying, ^ ^' },
  { id: 'lovestruck', label: 'Lovestruck', tags: 'looking at viewer, blush, happy, smile, tareme, heart-shaped pupils, seductive smile, hand on own chest, spoken heart, open mouth, loving aura' },
  { id: 'laughing', label: 'Laughing', tags: 'happy, smile, laughing, closed eyes, hand over own mouth, +++' },
  { id: 'looking_away_shyly', label: 'Looking Away Shyly', tags: 'averting eyes, looking to the side, embarrassed, blush, closed mouth, shy, finger to cheek, half-closed eyes, averting eyes, raised eyebrows, arm at side' },
  { id: 'nervous', label: 'Nervous', tags: 'looking at viewer, half-closed eyes, nervous, sweat, :<, raised eyebrows' },
  { id: 'proud', label: 'Proud', tags: 'closed eyes, smug, v-shaped eyebrows, closed mouth, hands on own hips' },
  { id: 'sad', label: 'Sad', tags: 'looking at viewer, sad, frown, raised eyebrows, parted lips, tearing up, hand on own chest, clenched hand' },
  { id: 'scared', label: 'Scared', tags: 'looking at viewer, turn pale, scared, shaded face, wavy mouth, open mouth, own hands together, hands on own face' },
  { id: 'shocked', label: 'Shocked', tags: 'looking at viewer, furrowed brow, surprised, wide-eyed, confused, constricted pupils, hands up, open mouth, rectangular mouth, wavy mouth, shaded face, constricted pupils, ^^^, !?' },
  { id: 'serious', label: 'Serious', tags: 'looking at viewer, serious, closed mouth, v-shaped eyebrows, furrowed brow, expressionless' },
  { id: 'sleepy', label: 'Sleepy', tags: 'looking at viewer, sleepy, rubbing eyes, :o, one eye closed, half-closed eyes, arm at side' },
  { id: 'smug', label: 'Smug', tags: 'looking at viewer, smug, smirk, :3, closed mouth, crossed arms' },
  { id: 'surprised', label: 'Surprised', tags: 'looking at viewer, surprised, open mouth, wide-eyed, hand to own mouth, hand on own face, ^^^' },
  { id: 'thinking', label: 'Thinking', tags: 'looking up, frown, hand on own chin, stroking own chin, thinking, furrowed brow, ...' },
  { id: 'worried', label: 'Worried', tags: 'looking at viewer, worried, confused, sweat, parted lips, wavy mouth, furrowed brow, raised eyebrows, own hands together, clenched hands' },
  { id: 'childlike_whining', label: 'Childlike Whining', tags: 'closed eyes, > <, :<, clenched hands, flying sweatdrops, blush, furrowed brow' },
  { id: 'excited', label: 'Excited', tags: 'looking at viewer, +_+, sparkling eyes, happy, smile, open mouth, :D, clenched hands, own hands together, excited, wide-eyed' },
  { id: 'suspicious', label: 'Suspicious', tags: 'looking at viewer, jitome, :<, closed mouth, raised eyebrow, uneven eyes, frown, v-shaped eyebrows, furrowed brow, stroking own chin, hand on own chin' },
  { id: 'admiring', label: 'Admiring', tags: 'looking at viewer, happy, smile, open mouth, head tilt, own hands together, own hands clasped, hand on own face, hand on own cheek' },
  { id: 'sniggering', label: 'Sniggering', tags: 'looking at viewer, smirk, smile, wavy mouth, half-closed eyes, tareme, closed mouth, hand over own mouth, covering mouth, raised eyebrows' },
  { id: 'relieved', label: 'Relieved', tags: 'closed eyes, u u, hand on own chest, open mouth' },
  { id: 'lustful', label: 'Lustful', tags: 'looking at viewer, shaded face, half-closed eyes, glowing eyes, heart-shaped pupils, naughty face, closed mouth, licking lips, :p, seductive smile, finger to mouth, heavy breathing, arm at side, blush' },
  { id: 'pouting', label: 'Pouting', tags: 'looking at viewer, pout, crossed arms' },
  { id: 'nervous_pouting', label: 'Nervous Pouting', tags: 'looking at viewer, nervous, clenched hands, open mouth, wavy mouth, v-shaped eyebrows, @ @, sweat' },
  { id: 'bored', label: 'Bored', tags: 'looking at viewer, bored, hand on own cheek, annoyed, frown, disappointed, raised eyebrows, one eye closed, open mouth, jitome' },
  { id: 'determined', label: 'Determined', tags: 'looking at viewer, v-shaped eyebrows, smile, open mouth, clenched hand, arm at side' },
  { id: 'jealous', label: 'Jealous', tags: 'looking at viewer, jealous, shaded face, anger vein, angry, expressionless, :<, crossed arms, half-closed eyes, uneven eyes' },
  { id: 'pleading', label: 'Pleading', tags: 'palms together, own hands together, praying, closed eyes, furrowed brow, raised eyebrows, wavy mouth, head down, flying sweatdrops' },
  { id: 'exhausted', label: 'Exhausted', tags: 'looking at viewer, exhausted, bags under eyes, parted lips, wavy mouth, mouth drool, sanpaku, half-closed eyes, frown, raised eyebrows, messy hair' },
  { id: 'happy_tears', label: 'Happy Tears', tags: 'closed eyes, happy tears, tears, rubbing eyes, wiping tears, open mouth, happy, smile' },
  { id: 'overwhelmed', label: 'Overwhelmed', tags: 'looking up, @_@, :o, furrowed brow, half-closed eyes, raised eyebrows, drooling, aroused' },
  { id: 'spacey', label: 'Spacey', tags: 'looking at viewer, expressionless, o_o, white eyes, no pupils, blank eyes, :o, jitome, arms at sides' },
  { id: 'middle_finger', label: 'Middle Finger', tags: 'looking at viewer, middle finger, furrowed brow, clenched teeth, parted lips, frown, angry, anger vein' },
  { id: 'taunting', label: 'Taunting', tags: 'looking at viewer, doyagao, akanbe, eyelid pull, :p, tongue out, raised eyebrows' },
  { id: 'acting_coy', label: 'Acting Coy', tags: 'looking at viewer, turning head, facing to the side, blush, happy, shy, open mouth, raised eyebrows, half-closed eyes, hands on own cheeks, hands on own face, hands up' },
  { id: 'smirk', label: 'Smirk', tags: 'looking at viewer, smirk, furrowed brow, closed mouth, jitome' },
  { id: 'chuunibyou', label: 'Chuunibyou', tags: 'looking at viewer, chuunibyou, double \\m/, crossed wrists, hands up, v-shaped eyebrows, :d, open mouth' },
  { id: 'cozy', label: 'Cozy', tags: 'closed eyes, = =, happy, open mouth, blush stickers, flower symbol' },
  { id: 'tormented', label: 'Tormented', tags: 'black eyes, wavy eyes, squiggle eyes, constricted pupils, looking down, furrowed brow, shaded face, scared, trembling, hands on own face, parted lips, despair, tears, streaming tears, sweat, gloom (expression)' },
  { id: 'grudging', label: 'Grudging', tags: 'looking to the side, averting eyes, shaded face, sigh, raised eyebrows, jitome, frown, parted lips, false smile' },
  { id: 'seductive_smile', label: 'Seductive Smile', tags: 'looking at viewer, seductive smile, blush, naughty face, finger to mouth, half-closed eyes' },
  { id: 'crazy_smile', label: 'Crazy Smile', tags: 'looking at viewer, shaded face, crazy smile, constricted pupils, happy, crazy eyes, ringed eyes, open mouth, leaning forward' },
  { id: 'evil_smile', label: 'Evil Smile', tags: 'looking at viewer, head down, shaded face, evil smile, half-closed eyes, parted lips, hand on own chin, clenched hand, head tilt' },
  { id: 'happy_smile', label: 'Happy Smile', tags: 'looking at viewer, happy, open mouth, smile, closed eyes, hand on own stomach, happy aura' },
  { id: 'forced_smile', label: 'Forced Smile', tags: 'looking at viewer, half-closed eyes, closed mouth, forced smile, frown, furrowed brow, raised eyebrows, smile, :>, sweat, nervous' },
  { id: 'playful_wink', label: 'Playful Wink', tags: 'looking at viewer, one eye closed, open mouth, happy, smile, raised eyebrows, v over eye, peace sign, > o' },
  { id: 'enraged', label: 'Enraged', tags: 'looking at viewer, shaded face, tsurime, furious, constricted pupils, veins, narrowed eyes, v-shaped eyebrows, furrowed brow, parted lips, wavy mouth, scowl, teeth' },
  { id: 'bridling', label: 'Bridling', tags: 'looking at viewer, angry, shaded face, half-closed eyes, parted lips, clenched teeth, frown, sulking, v-shaped eyebrows, veins, arms at sides' },
  { id: 'eureka', label: 'Eureka', tags: 'looking at viewer, spoken light bulb, open mouth, happy, index finger raised, hand up' },
  { id: 'stupefied', label: 'Stupefied', tags: 'looking at viewer, open mouth, rectangular mouth, mouth drool, jaw drop, no pupils, white eyes, wide-eyed, furrowed brow, frown, confused, !?' },
  { id: 'angry_smile', label: 'Angry Smile', tags: 'closed eyes, ^ ^, :), angry, shaded face, furrowed brow, raised eyebrows, anger vein' },
  { id: 'dozing_off', label: 'Dozing Off', tags: 'closed eyes, parted lips, drooling, mouth drool' },
  { id: 'acting_cute', label: 'Acting Cute', tags: 'looking at viewer, fingers to cheeks, pointing at self, happy, tareme, puckered lips, puffy cheeks' },
  { id: 'stretching', label: 'Stretching', tags: 'closed eyes, stretching, arms up, arm behind head, furrowed brow' },
  { id: 'head_bump', label: 'Head Bump', tags: 'closed eyes, teardrop, open mouth, wavy mouth, furrowed brow, raised eyebrows, hands on own head, head bump, crossed bandaids, injury, head steam' },
];